name: Publish Docker Image

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    name: Build and Push Docker Image
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
    # Step 1: Checkout the code
    - name: Checkout repository
      uses: actions/checkout@v3

    # Step 2: Log in to GitHub Container Registry (GHCR)
    - name: Log in to GitHub Container Registry
      run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

    # Step 3: Build the Docker image
    - name: Build Docker image
      run: |
        docker build -t ghcr.io/eimrek/tiny-fastapi-mongo-app:latest .

    # Step 4: Push the Docker image to GHCR
    - name: Push Docker image
      run: |
        docker push ghcr.io/eimrek/tiny-fastapi-mongo-app:latest